### ISSUE TITLE
Switch to a SQL database

### ISSUE THREAD

**Issue by not-an-aardvark** [porybox/porybox#279]
I think we should switch to a SQL database, preferably sooner rather than later.

MongoDB's lack of support for transactions is making a few server tasks difficult and potentially dangerous. For example, we can't use a linked-list to allow the contents of a box to be reordered (since we can't atomically write to more than one document at once), so we're just storing a separate list of IDs on the box itself. This can result in things being left in an inconsistent state if the server loses connection with the database, or if the server is stopped at the wrong time.

Since we're using waterline anyway, I don't think the migration to something like postgres would be too difficult. Our models don't have any nested structures anyway (with the exception of the `User` model), and the only notable thing we have to refactor would be the logic for box ordering.

**Comment by NotRaia** [comment]
If we want to do this, we may want to reconsider tomorrow's public beta, or just make it very clear that we're not responsible if anything is lost.

**Comment by not-an-aardvark** [comment]
I think we can still release and then do a migration later on.

There are a few sanity checks we can put in place while fetching a box to ensure that no IDs are missing, and to restore them to the end of the box if they are missing. It's not a great solution, but it should prevent stuff from going missing entirely.

(To be clear, I don't think anything will get deleted entirely, but at the moment it's possible for it to not appear in a box correctly because the list of IDs got out of sync.)

**Comment by YaManicKill** [comment]
If we are doing this, we either do it before public release or we wipe the
database. We are not doing a migration between different databases. That
just makes things awkward. Very awkward.

**Comment by not-an-aardvark** [comment]
> If we are doing this, we either do it before public release or we wipe the
database.

Neither of those sound like good options, honestly. Could you elaborate on how the migration would make things very awkward? (It would be a bit tricky, certainly, but I imagine we could write/test a script to handle everything.)

**Comment by YaManicKill** [comment]
So, as mentioned on IRC:

1. The amount of time spent on a script is incredibly wasteful, when we have so much more we need/want to do on this
2. There will be lots of small niggly bugs that we won't forsee. Even if we write a script that appears to do everything we want, and we have tests for it, there will still be lots of bugs based on the data that comes out of it, and that will take up a load of time

Personally, I think we should delay the release and sort this out before.

**Comment by YaManicKill** [comment]
Also, regarding writing to more than 1 document at once.

https://docs.mongodb.com/manual/core/write-operations-atomicity/#isolated-operator

**Comment by NotRaia** [comment]
I agree that if we really need to switch, we should delay the release.

Let's discuss it and make a decision as soon as you're back on IRC, naa.

**Comment by YaManicKill** [comment]
How realistic is this that we will ever do now?

**Comment by not-an-aardvark** [comment]
I still think it would be nice, but it's not a high priority. Closing for now.
