### ISSUE TITLE
Use animated sprites?

### ISSUE THREAD

**Issue by TheSonAlsoRises** [porybox/porybox#471]
Re: https://www.reddit.com/r/porybox/comments/4y2zt7/suggestion_animated_sprites/

Standard sprites:  http://media.pldh.net/docs/monster_sprites_gen6_animated.rar
Shiny sprites: http://media.pldh.net/docs/monster_sprites_gen6_animated_shiny.rar

**Comment by YaManicKill** [comment]
I'm going to say this is probably unnecessary, increases our load and we don't really care. Plus we are having issues with trying to get the sprites for every pokemon to be consistent anyway.

**Comment by TheSonAlsoRises** [comment]
Agreed, it would be more distracting than anything else. I will close it.
