### ISSUE TITLE
Empty box indicator

### ISSUE THREAD

**Issue by Kirzi** [porybox/porybox#522]
Super minor suggestion: Some sort of indicator in the box view that says that the box is currently empty. 

We could also stick an extra upload button there or something for easier usability.

**Comment by YaManicKill** [comment]
This is a good plan. My suggestion:

Have a pokemon-sized slot which says "Your box is empty, click here to add some", it should also have a large upload icon, and when you click on the whole box, it pops up the upload form.

**Comment by YaManicKill** [comment]
@Raia Obviously, this isn't a priority, but I know you were working on this. 

If it's nearly done, do you want to get a PR up so we can get it in with 1.3 (gen 7 changes)? If not, I'll put it in for 1.4.
