### ISSUE TITLE
Allow users to upload pk7s

### ISSUE THREAD

**Issue by YaManicKill** [porybox/porybox#541]
So, a couple of things:

* We will add a new endpoint for pk7s (because the backend doesn't get the extension)
* We will remove support for pkxs
* We will change _rawpk6 to _rawFile
* We will add either generation or extension to the pokemon to distinguish between them
* pk6parse will get a new parsing mode

**Comment by Kirzi** [comment]
A few more things to do, since some stuff gets wiped on pk6 > pk7 transfer:

- Remove the "encounter type" line for gen 4 Pokemon 
- Remove the secret training enabled line for pk7s

**Comment by Certerazvi** [comment]
Hi, guys! :) Any idea when pk7 upload will be available?

**Comment by YaManicKill** [comment]
@Certerazvi I've been ridiculously busy moving hosue, so it has slipped a little. Hoping the next few weeks.
