### ISSUE TITLE
Add hyper training indication

### ISSUE THREAD

**Issue by YaManicKill** [porybox/porybox#545]
Remember that hyper training doesn't set the IV to 31, it's a seperate bit.

Reaaaaally not sure what the best way to show this is.

**Comment by Raia** [comment]
We can make a new column in the stats table for "Hyper Trained? y/n", or another option would be to change the text color for stats that are Hyper Trained.

**Comment by YaManicKill** [comment]
Yeah. I think the first option is best. Second is a bit confusing.

**Comment by YaManicKill** [comment]
Assuming you don't do it tonight, @Raia, I'll get this done tomorrow.
