### ISSUE TITLE
Support for the updated Pokémon Bank

### ISSUE THREAD

**Issue by TheSonAlsoRises** [porybox/porybox#609]
https://twitter.com/SciresM/status/823903445732196355

<Keima> I've hacked in a few Eevees  with game origins between 0x20 and 0x29.  0x20 and 0x21 shows Alola native.  0x22 shows a G in a circle, 0x23 is the GB icon recently revealed by Nintendo HK.

(0x23 to 0x29 for the GB icon)

https://twitter.com/SciresM/status/823906036377452544

**Comment by YaManicKill** [comment]
Only 0x23, 0x24, and 0x25 are legal after bank, though. R, B, and Y respectively.

**Comment by YaManicKill** [comment]
Oh wait, sorry. 0x23-0x26. I forgot about Green.

**Comment by YaManicKill** [comment]
Split into #657 and #658 

I think that's all we need to support in porybox from this? Feel free to add another one if I've missed something.
