### ISSUE TITLE
Gen 7 ID No is not correctly formatted on card view

### ISSUE THREAD

**Issue by SnowPhoenix** [porybox/porybox#678]
* TIDs show up correctly on the mini-card box listing when initially uploading, but show up incorrectly when loading existing Pokémon because the wrong field is loaded and referenced

> Interpreting socket.io message as virtual request to "get /api/v1/box/[...],speciesName,**tid**,visibility

**Comment by YaManicKill** [comment]
> TIDs show up correctly on the mini-card box listing when initially uploading, but show up incorrectly when loading existing Pokémon because the wrong field is loaded and referenced

Hmmm, but it should be backwards compatible, as all existing pokemon will be gen 6, so the tid will be the right thing.

**Comment by YaManicKill** [comment]
> SID is still displayed for Gen 7 Pokémon. Some conversions may be needed before relying on this exclusively, but per previous discussion, this should be replaced by TID (full) for all Pokémon, with SID being added as a "derived" value (like TSV) for Pokémon in generations where it is reasonably useful (5 and below?)

Can you split this into a different issue. But yeah, that's a good point.

**Comment by SnowPhoenix** [comment]
> Hmmm, but it should be backwards compatible, as all existing pokemon will be gen 6, so the tid will be the right thing.

idNo is supposed to be the "accurate for any gen" piece of data, with tid becoming deprecated since @not-an-aardvark was concerned that people using pkparse may end up with broken code if we change that to something that can result in a >5 digit number. Now that you bring it up, I'm guessing this does mean we need to create idNo attributes for existing items in the database, though. >_<

**Comment by YaManicKill** [comment]
> idNo is supposed to be the "accurate for any gen" piece of data,

Yes, but we would have to run every existing pokemon through the parser again to get idNo on them. So I'm using tid if idNo doesn't exist. Because it's right for gen 6.

> Now that you bring it up, I'm guessing this does mean we need to create idNo attributes for existing items in the database, though. >_<

I'm not sure I understand the issue if this isn't it...

**Comment by YaManicKill** [comment]
Alright, I'm seeing the issue.

On gen 7 pokemon, it shows the ID as 5 digits in box view, but in pokemon view it shows as 6 digits.
