### ISSUE TITLE
Change SID

### ISSUE THREAD

**Issue by SnowPhoenix** [porybox/porybox#679]
Split from #678.

SID is still displayed for Gen 7 Pokémon. Some conversions may be needed before relying on this exclusively, but per previous discussion, this should be replaced by ID No (full) for all Pokémon, with SID being added as a "derived" value (like TSV) for Pokémon in generations where it is reasonably useful (5 and below?)

The discussion from the other issue reminded me that we planned on changing "TID" to "ID No" on the front-end as well for consistency with the games.

**Comment by YaManicKill** [comment]
Alrighty.

Suggestion: show sid for gen 6 pokemon (to make it consistent with what we've been doing up to now, and because existing pokemon don't have that, also sid means something for gen 6, whereas the full one doesn't really) and show tidfull for gen 7 pokemon.

**Comment by YaManicKill** [comment]
> The discussion from the other issue reminded me that we planned on changing "TID" to "ID No" on the front-end as well for consistency with the games.

I'm movign this to another ticket

**Comment by YaManicKill** [comment]
Did we ever agree about what to do about this?

**Comment by YaManicKill** [comment]
Right, I've had no other feedback on this.

Here are the different things we have:

* idNo (that is 5 digits for pre-7 stuff, and 6 digits for 7 stuff)
* tidfull (the full 32 bit tid, which includes the hidden and the visible parts)
* sid (The hidden part of the tidfull)

The current suggestion:

* Gen 7 pokemon: show idNo and tidfull
* Pre-7 pokemon (including pokemon transferred to gen 7): show idNo and sid

I would have preferred to just show the idNo and the tidfull for all pokemon, but it appears there are still some uses for the sid, even when you've transferred it up to gen 7 (ask @Kirzi). So I guess this makes the most sense.

I will go ahead and implement this unless people suggest something else.
