### ISSUE TITLE
Adjustments to markings

### ISSUE THREAD

**Issue by SnowPhoenix** [porybox/porybox#703]
I made some alternate SVGs that hopefully represent the Gen 7 clover and VC Game Boy shapes a bit better so I'm planning to try them out.

In addition, the RGB colors for the blue/pink markings are known, so I plan on switching them to be more game accurate. The blue in particular looks rather far off at the moment.

These shouldn't take long once I have other, more major stuff out of the way.

**Comment by YaManicKill** [comment]
> In addition, the RGB colors for the blue/pink markings are known, so I plan on switching them to be more game accurate. The blue in particular looks rather far off at the moment.

Ah yes, I just chose default blue and pink. Good plan.

> I made some alternate SVGs that hopefully represent the Gen 7 clover and VC Game Boy shapes a bit better so I'm planning to try them out.

Yes please, mine are pretty crappy.

**Comment by SnowPhoenix** [comment]
Done and merged in #721.
