### ISSUE TITLE
Support for alternate Pikachu forms

### ISSUE THREAD

**Issue by SnowPhoenix** [porybox/porybox#705]
This one's for further down the road, but we should probably do it eventually. This will require making sprite selection capable of selecting a sprite based on the gen. In the case of the box sprites, this could be accomplished via an additional (optional) class, but it will require a different solution for the large sprites where it's applicable (in addition to actually deciding what to use for the large sprites for cosplay Pikachu's, since they don't actually have different sprites for the different costumes in the ORAS Pokédex).

**Comment by YaManicKill** [comment]
Yeah, this is something we should do, but let's not do it for 1.3. We already don't support cosplay pikachu, so not supporting the hat pikachus is fine for now (especially as the hat pikachus aren't out yet).

But we can target the next release after this one?

**Comment by SnowPhoenix** [comment]
Discussed this with you via IRC, but I'll leave a comment for any others reading. This was *not* intended to be among the goals for 1.3, but just a note of something we should support later on. 1.4? Maybe, we'll see, but it's really just an "eventually" for now.

**Comment by YaManicKill** [comment]
We shall leave it un-milestoned then.
