### ISSUE TITLE
Scrolling on Chrome for Android is messed up 

### ISSUE THREAD

**Issue by YaManicKill** [porybox/porybox#713]
I think this has to do with the swiping between tabs, but when you try and scroll on a Pokémon, you either change tabs, or nothing happens. Not great.

**Comment by SnowPhoenix** [comment]
Adding a few details from IRC discussion:

* This bug affects Chrome for Android specifically. iOS browsers, as well as the stock Android browser (on 4.4 at least) are fine.
* On Chrome for Android, this bug prevents scrolling entirely while on top of elements that are part of the md-tabs element on Pokémon pages.
* On the current production version of the site, scrolling is possible, but it will unpredictably scroll to tabs to the right while trying to scroll up or down. Although it has not been tested, #715 will presumably help with that issue, but it does not help with scrolling on the current development version.

**Comment by not-an-aardvark** [comment]
Not fixed yet, see #716
