### ISSUE TITLE
Generation 7 save files not supported

### ISSUE THREAD

**Issue by TheSonAlsoRises** [porybox/porybox#718]
It appears generation 7 main files cannot be loaded on Porybox.

Example file: https://www.dropbox.com/s/e8qna4da4y7y2af/save?dl=0

Relevant js: https://github.com/porybox/porybox/blob/master/client/add/parseSaveFile.js

**Comment by YaManicKill** [comment]
> It appears

Maybe because no one has ever mentioned this...

It's not a bug, it just hasn't been implemented.

**Comment by TheSonAlsoRises** [comment]
According to @Cu3PO42, the offset should be 0x4e00, as per https://github.com/Cu3PO42/KeySAVCoreJS/blob/master/save-reader-decrypted.ts

**Comment by YaManicKill** [comment]
I'll get this done this morning as no one else has started yet.
