### ISSUE TITLE
Creating a box with the same name as an already existing box error

### ISSUE THREAD

**Issue by pkmnbumba** [porybox/porybox#741]
States that an unexpected error has occurred but still creates a new box (1.3 beta)

**Comment by YaManicKill** [comment]
Hey, bumba. I'm not managing to recreate this myself. can you show us a gif of it happening, and maybe get the errors from the Javascript console? Thanks.

**Comment by YaManicKill** [comment]
As no one can reproduce (not even bumba anymore) I'm going to assume this was a weird temporary caching issue and close unless we see it again.
