### ISSUE TITLE
HP hyper training not checked when it should

### ISSUE THREAD

**Issue by Kirzi** [porybox/porybox#780]
![poryboxbug1](https://cloud.githubusercontent.com/assets/11909976/25002983/2c0b200c-201b-11e7-8fd0-a651c7a86ddf.PNG)

![poryboxbug2](https://cloud.githubusercontent.com/assets/11909976/25002935/f7ab7e60-201a-11e7-971a-38aa2785a878.PNG)

**Comment by YaManicKill** [comment]
Commit accidentally pushed to master. Reverted, so reopneing.
