### ISSUE TITLE
Add "Copy to Clipboard" Option for Basic pkm Data (Pokeball, Pokemon, Nature, IVs, OT/ID, TSV )

### ISSUE THREAD

**Issue by tacocat777** [porybox/porybox#795]
When trading, it would be nice if the user could click a button and instantly copy a pkm's data to the user's clipboard. Wonder what data should be included/omitted. Installing a clipboard.js package may be the easiest way, but I considered maybe embedding a C# winforms app. Something like this: https://i.imgur.com/Omb08b1.jpg

**Comment by Raia** [comment]
Looks like a duplicate of #34.

**Comment by tacocat777** [comment]
Sorry, I looked for copy to clipboard!

**Comment by Raia** [comment]
No worries! Thanks for posting, it's nice to see some activity here :)
