### ISSUE TITLE
Empty Box

### ISSUE THREAD

**Issue by DDR1717** [porybox/porybox#797]
Hi! Today I added a Pokémon in one of my box and when this box is empty. If I am in my Porybox's Homepage I see the icon for this box, but when I open the box...is empty! :(

**Comment by Raia** [comment]
Hi, what's your username on Porybox? Could you post a link to the box?

If you were trying to upload something exclusive to USUM, Porybox doesn't support USUM yet, but we're working on it!

**Comment by DDR1717** [comment]
Hi! I'm DDR_17 on Porybox and [this](https://www.porybox.com/#/box/8b16d013a5f8fda4b394b26e7792ae20) is the box! :)

**Comment by Raia** [comment]
Thanks! What were you trying to upload?

**Comment by DDR1717** [comment]
30 minutes ago

**Comment by Raia** [comment]
What was the Pokémon?

**Comment by DDR1717** [comment]
A Shiny Eevee

**Comment by Raia** [comment]
Hmm, what game was the shiny Eevee from? Could you try uploading it again in a different browser, or in an incognito window with all of your browser extensions disabled?

>If I am in my Porybox's Homepage I see the icon for this box

Could you attach a screenshot of that here too?

**Comment by DDR1717** [comment]
From US

[Image](https://drive.google.com/file/d/1mqbTx0KflRFoT_afwNaXr9aiPCA3lxTz/view?usp=sharing). The box is Shinies

**Comment by Raia** [comment]
Thanks for the info. It looks like this was another case of #536 – we've fixed your box manually and you should be able to see everything now. Sorry for the trouble!
