### ISSUE TITLE
Problem with USUM Pokemon Upload

### ISSUE THREAD

**Issue by Koroze23** [porybox/porybox#800]
Hi, I cant upload Necrozma (with Ultranecrozium Z), Blachepalon and Stakataka in my Porybox :(

**Comment by TheSonAlsoRises** [comment]
Hi,

USUM support is being worked on. You should be able to upload the new Pokémon/items soon.

**Comment by Raia** [comment]
USUM support is now live. Let us know if you run into any issues!
